In [51]:
import numpy as np

In [52]:
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)

In [53]:
apartment = np.array([59.50,31.40,19, 22, 60550,2])
share_living_space = apartment[1]/apartment[0]
apartment = np.delete(apartment, [0, 1])
apartment = np.append(apartment, share_living_space)

In [54]:
apartment

array([   19.   ,    22.   , 60550.   ,     2.   ,     0.528])

In [55]:
print (round(apartment[-1], 2))

0.53


In [56]:
print("ap shape:", apartment.shape)

ap shape: (5,)


In [59]:
t = np.array([12, 14, 17, 19, 24, 28, 31, 31, 27, 22, 17, 13])
print(t[2], t[5])

17 28


In [62]:
v = np.array([-1,4,6,1,8,2])
print (v.shape, v.ndim, v[3])

(6,) 1 1


In [67]:
a=np.array([65,70,120,30])
b=np.array([0.4,0.4,0.2,0.8])
np.dot(a,b)

102.0

In [78]:
alexRur = np.array([120, 150, 90]) 
wifeRur = np.array([130, 130, 130]) 
tshaEur = np.array([2,3,2.5]) 
tshaRur = tshaEur * 72 
print(tshaRur)
print(alexRur + wifeRur + tshaRur)

[144. 216. 180.]
[394. 496. 400.]
